server:
  port: ${SERVER_PORT:8081}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: /

security:
  internal:
    header:
      name: ${INTERNAL_SECURITY_HEADER:X-Gateway-Token}
      value: ${INTERNAL_SECURITY_VALUE:token}