server:
  port: ${SERVER_PORT:0}
  servlet:
    context-path: /ms-booking

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/flighty}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:xiaominote9}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: ${SPRING_LIQUIBASE_ENABLED:true}
    change-log: classpath:liquibase/changelog-master.yml
    drop-first: false
    default-schema: ${FLIGHTY_DB_SCHEMA:public}
    database-change-log-table: BOOKINGMS_DBCHANGELOG
    database-change-log-lock-table: BOOKINGMS_DBCHANGELOGLOCK
  jpa:
    hibernate:
      ddl-auto: none

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  server:
    enableSelfPreservation: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: /

security:
  internal:
    header:
      name: ${INTERNAL_SECURITY_HEADER:X-Gateway-Token}
      value: ${INTERNAL_SECURITY_VALUE:token}


client:
  url:
    auth: ${AUTH_MS_URL:http://localhost:8081/auth-ms/}
    user: ${USER_MS_URL:http://localhost:8081/ms-user/}
    flight: ${FLIGHT_MS_URL:http://localhost:8081/ms-flight/}

feign:
  client:
    config:
      default:
        loggerLevel: full