server:
  port: ${SERVER_PORT:0}
  servlet:
    context-path: /ms-flight

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  server:
    enableSelfPreservation: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: /

security:
  internal:
    header:
      name: ${INTERNAL_SECURITY_HEADER:X-Gateway-Token}
      value: ${INTERNAL_SECURITY_VALUE:token}


client:
  url:
    auth: ${AUTH_MS_URL:http://localhost:8081/auth-ms/}