CREATE
EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE public.location
(
    id BIGINT   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id UUID DEFAULT uuid_generate_v1(),
    city        VARCHAR(50) NOT NULL,
    airport     VARCHAR(50) NOT NULL
);

CREATE TABLE public.flight
(
    id BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_id           UUID DEFAULT uuid_generate_v1(),
    arrival_time        TIMESTAMP  NOT NULL,
    departure_time      TIMESTAMP  NOT NULL,
    price               NUMERIC    NOT NULL,
    arrival_location    BIGINT REFERENCES public.location(id),
    departure_location  BIGINT REFERENCES public.location(id),
    code                VARCHAR(50)  NOT NULL,
    status              VARCHAR(10)  NOT NULL,
    active              BOOLEAN NOT NULL
);